services:
  db:
    image: postgis/postgis:16-3.4
    container_name: suds-postgis
    restart: unless-stopped
    shm_size: "1gb"     
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: suds
      # POSTGRES_PASSWORD removed - will be in compose.override.yml
    ports:
      - "5432:5432"
    volumes:
      - suds_pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d suds"]
      interval: 5s
      timeout: 5s
      retries: 20
volumes:
  suds_pgdata: